#!/bin/bash
NIXIE_DIR=$HOME/Nixie-Display

nixie_print() {
    $NIXIE_DIR/nixie-boot/nixie_cat "$1" || \
        $NIXIE_DIR/send_text -n -c raspi "$1"
}

cd $NIXIE_DIR
#nixie_print "$(ip route get 8.8.8.8 | head -1 | cut -d' ' -f7)" && sleep 10
nixie_print "Pulling from Git"
git checkout nixie-live
BEFORE_HASH=$(git rev-parse HEAD)
git pull -f || echo "Failed to pull latest code from git"
AFTER_HASH=$(git rev-parse HEAD)

PIP_FLAG=/tmp/nixie_pip_done
if [[ ! -f $PIP_FLAG ]] || [[ "$BEFORE_HASH" != "$AFTER_HASH" ]]; then
    nixie_print "Checking pip"
    pip install -q --break-system-packages -r $HOME/Nixie-Display/requirements.txt || \
        pip install -q -r $HOME/Nixie-Display/requirements.txt
    touch $PIP_FLAG
fi
cd $HOME
nixie_print "Starting..."
$NIXIE_DIR/run_display -c raspi --keyboard-event-file /dev/input/event0 --extended-hours --git-check 5 --logfile logs/nixie.log --loglevel debug 2>logs/nixie.stderr
if [[ $? -ne 0 ]]; then
    nixie_print "Crashed"
else
    nixie_print "Waiting..."
fi
exit 1
