#!/bin/bash
# Control an on-demand WiFi access point on the nixie display's onboard radio,
# so the Pi can be reached over SSH when no external WiFi (or USB) is available.
# The Zero 2 W has a single radio: bringing the AP up REPLACES client WiFi, and
# bringing it down restores client mode (autoconnect to known networks).
#
# Requires root (it edits /etc and toggles services). Runnable by hand:
#   sudo scripts/wifi_ap_root.sh up   ~/.nixie/wifi_ap.conf
#   sudo scripts/wifi_ap_root.sh down
#   scripts/wifi_ap_root.sh status        # no root needed
#
# The run-once channel + the WiFiAPController menu item call this via `sudo -n`
# (whitelisted by `scripts/setup_audio_perms.sh --nopasswd`).
#
# Services are start/stop-ped, never `enable`d, so the AP is OFF after a reboot
# but persists across a run_display restart (see the deployment skill).
#
# `up` reads SSID/password from a conf file (keeps the secret off the argv):
#   ssid=nixie-control
#   password=neon-tube-backdoor-64
#
# Env overrides (for testing off-Pi):
#   WIFI_AP_ETC_DIR   /etc to write into (default /etc); setting it also enables
#                     "test mode": no root check, no systemctl/ip/dhcpcd calls.
#   WIFI_AP_IFACE     wireless interface (default wlan0)
set -u

ETC="${WIFI_AP_ETC_DIR:-/etc}"
WLAN="${WIFI_AP_IFACE:-wlan0}"
AP_IP="192.168.4.1"
AP_CIDR="$AP_IP/24"
HOSTAPD_CONF="$ETC/hostapd/hostapd.conf"
DNSMASQ_CONF="$ETC/dnsmasq.d/nixie-ap.conf"
SSID=""
PSK=""

usage() {
    cat <<'EOF'
Usage: wifi_ap_root.sh {up <conf_file>|down|status}
  up <conf_file>  bring the AP up using ssid=/password= from <conf_file>
  down            stop the AP and restore client WiFi
  status          print "on <ip>" or "off"
EOF
}

test_mode() {
    ## An explicit /etc override means we're testing off-Pi: only generate the
    ## config files, never touch root services or interfaces.
    [[ -n "${WIFI_AP_ETC_DIR:-}" ]]
}

read_conf() {
    local file="$1" line key val
    while IFS= read -r line; do
        key="${line%%=*}"
        val="${line#*=}"
        if [[ "$key" == "ssid" ]]; then
            SSID="$val"
        elif [[ "$key" == "password" ]]; then
            PSK="$val"
        fi
    done < "$file"
}

validate() {
    local n
    n=${#SSID}
    if [[ $n -lt 1 || $n -gt 32 ]]; then
        echo "Invalid SSID length ($n); must be 1-32 chars" >&2
        return 1
    fi
    n=${#PSK}
    if [[ $n -lt 8 || $n -gt 63 ]]; then
        echo "Invalid password length ($n); WPA2 requires 8-63 chars" >&2
        return 1
    fi
    return 0
}

write_hostapd_conf() {
    mkdir -p "$(dirname "$HOSTAPD_CONF")"
    cat > "$HOSTAPD_CONF" <<EOF
# Generated by wifi_ap_root.sh -- do not edit by hand
interface=$WLAN
driver=nl80211
ssid=$SSID
hw_mode=g
channel=7
auth_algs=1
ignore_broadcast_ssid=0
wpa=2
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
wpa_passphrase=$PSK
EOF
    chmod 600 "$HOSTAPD_CONF"
}

write_dnsmasq_conf() {
    mkdir -p "$(dirname "$DNSMASQ_CONF")"
    cat > "$DNSMASQ_CONF" <<EOF
# Generated by wifi_ap_root.sh -- do not edit by hand
interface=$WLAN
bind-dynamic
domain-needed
bogus-priv
dhcp-range=192.168.4.10,192.168.4.100,255.255.255.0,24h
dhcp-option=3,$AP_IP
dhcp-option=6,$AP_IP
EOF
}

ensure_hostapd_daemon_conf() {
    ## The Debian hostapd.service reads DAEMON_CONF from here; if it's empty the
    ## service starts with no config and fails. Point it at our generated file.
    local f="$ETC/default/hostapd" body
    if [[ ! -f "$f" ]]; then
        return
    fi
    if grep -qxF "DAEMON_CONF=\"$HOSTAPD_CONF\"" "$f"; then
        return
    fi
    body=$(grep -vE '^#?DAEMON_CONF=' "$f")
    printf '%s\nDAEMON_CONF="%s"\n' "$body" "$HOSTAPD_CONF" > "$f"
}

stop_client_wifi() {
    ## hostapd and wpa_supplicant fight over the single radio: if the supplicant
    ## keeps wlan0 in "managed" mode it re-associates to a known network right
    ## after hostapd enables the AP, so hostapd stays "active" but never beacons
    ## (the interface shows `type managed`, not `type AP`). dhcpcd -k alone does
    ## NOT stop it on Bullseye. Tell the supplicant on this interface to quit,
    ## then fall back to killing any still bound to it.
    wpa_cli -i "$WLAN" terminate >/dev/null 2>&1 || true
    if pgrep -f "wpa_supplicant.*$WLAN" >/dev/null 2>&1; then
        pkill -f "wpa_supplicant.*$WLAN" || true
    fi
}

do_up() {
    write_hostapd_conf
    write_dnsmasq_conf
    if test_mode; then
        echo "AP up: generated configs under $ETC (test mode; services not started)"
        return 0
    fi
    ensure_hostapd_daemon_conf
    rfkill unblock wlan 2>/dev/null || true
    ## Free wlan0 from client mode without disturbing other interfaces (usb0).
    stop_client_wifi
    dhcpcd -k "$WLAN" 2>/dev/null || true
    ip addr flush dev "$WLAN" || true
    ip link set "$WLAN" up || true
    ip addr add "$AP_CIDR" dev "$WLAN" || true
    systemctl unmask hostapd 2>/dev/null || true
    systemctl restart dnsmasq
    systemctl restart hostapd
    echo "AP up: broadcasting '$SSID' at $AP_IP"
}

do_down() {
    if test_mode; then
        echo "AP down (test mode)"
        return 0
    fi
    systemctl stop hostapd 2>/dev/null || true
    systemctl stop dnsmasq 2>/dev/null || true
    ip addr flush dev "$WLAN" || true
    ## hostapd left the radio in AP mode; put it back to managed and bounce the
    ## link so the supplicant can re-associate.
    ip link set "$WLAN" down || true
    iw dev "$WLAN" set type managed 2>/dev/null || true
    ip link set "$WLAN" up || true
    ## Rebind via dhcpcd: re-runs its wpa_supplicant hook so client WiFi resumes
    ## and autoconnects to known networks (no reboot needed).
    dhcpcd -n "$WLAN" 2>/dev/null || true
    echo "AP down: restored client WiFi on $WLAN"
}

do_status() {
    local ip
    if ! test_mode && systemctl is-active --quiet hostapd; then
        ip=$(ip -4 -o addr show "$WLAN" 2>/dev/null | grep -oE 'inet [0-9]+(\.[0-9]+){3}' | head -1 | cut -d' ' -f2)
        echo "on ${ip:-$AP_IP}"
    else
        echo "off"
    fi
}

main() {
    local action="${1:-}"
    case "$action" in
        -h|--help) usage; exit 0 ;;
        status)    do_status; exit 0 ;;
    esac

    if ! test_mode && [[ $EUID -ne 0 ]]; then
        echo "Must be run as root (try: sudo $0 $action)" >&2
        exit 1
    fi

    case "$action" in
        up)
            local conf="${2:-}"
            if [[ -z "$conf" || ! -f "$conf" ]]; then
                echo "up requires a readable conf file: up <conf_file>" >&2
                exit 1
            fi
            read_conf "$conf"
            if ! validate; then
                exit 1
            fi
            do_up
            ;;
        down)
            do_down
            ;;
        *)
            usage
            exit 1
            ;;
    esac
}

main "$@"
